import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Recipe Finder",
	description: "Generated by create next app",
	icons: {
		icon: ["/favicon-16x16.png"],
		apple: ["/favicon-16x16.png"],
		shortcut: ["/favicon-16x16.png"],
	},
	manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
