import { Inter } from "next/font/google";
import "./globals.css";
import Container from "@/components/container/container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={inter.className}
				style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}
			>
				<Container style={{ flex: 1 }}>{children}</Container>
			</body>
		</html>
	);
}
